apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: workshop
  creationTimestamp: null
  labels:
    app: my-notes
spec:
  ports:
  - name: 4000-4000
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: front-svc
  type: NodePort
status:
  loadBalancer: {}
