apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
type: kubernetes.io/basic-auth
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: admin # required field for kubernetes.io/basic-auth
