apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workshop
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
        - name: frontend
          image: loka07/notes:v5
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-svc.workshop:27017/notesdb"  # Adjust database name if needed
          ports:
            - containerPort: 4000